import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>K Excel to Table</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div id={styles["home"]}>
      <h2>Kroger .xlsx File Converter</h2>
      <div id={styles["navigation"]}>
        <Link href="/posts/Report" passHref>
          <button>Report</button>
        </Link>
        <Link href="/posts/Employees" passHref>
          <button>Employees</button>
        </Link>
      </div>
        </div>
    </div>
  );
};

export default Home;
